### ISSUE TITLE
Dependencies not automatically installed

### ISSUE THREAD

**Issue by alexleach** [alexleach/DompdfRendererBundle#2]
When running `./bin/console kimai:reload`, I'd expect the dependency required in this plugin's `composer.json` to be automatically installed. Well, I'd expect some command to install the plugin's dependency, but can't figure out an easy command to do so.

Therefore, the current recommendation is to explicitly enter the command `composer require dompdf/dompdf`, which doesn't seem right. It also then modifies the top-level `composer.json` file...

How should a Kimai / Symfony plugin's dependencies actually be installed?

**Comment by alexleach** [comment]
@kevinpapst, I wondered if you might know the answer to this? I couldn't find any obvious answers in the Kimai or the Symfony docs about installing plugin dependencies, but assume this should be pretty easy to do?

**Comment by kevinpapst** [comment]
Use composer to install them. There is no other way.
But there needs to be a strong reason for that, as it will conflict during updates, as 99% of all users have no understanding of git merge conflicts in composer.json / composer.lock files.
What dependency are you thinking about?

**Comment by alexleach** [comment]
Hi @kevinpapst, thanks for the quick reply!
Just dompdf/dompdf. I have it in my composer.json file, which resides in `/opt/kimai/var/plugins/DompdfRendererBundle/`.

So, currently to install dompdf, I'm suggesting go to `/opt/kimai` and enter:-

```
composer require dompdf/dompdf
```

Which then adds the requirement to `/opt/kimai/composer.json`

Is that how you'd suggest it be installed? Kind of makes the `require` and `require-dev` blocks of my plugin's `composer.json` completely pointless, other than just a point of reference...

**Comment by kevinpapst** [comment]
Yes, that's how you have to do it currently.

Right now, your own composer entries are not used (the composer.json is read by Kimai, but not by composer) ... 

If you would have cloned the [DemoBundle](https://github.com/keleo/DemoBundle), you would have some CI setup, which would use composer to install your dependencies.

So having your dependency in there is not "pointless"! Yes, the plugins are not yet full fledged composer packages. But it is still good if you have everything in place. I have ideas how to add better support for installing dependencies and then this will be used.

But until then, people have to rely on your docs.

**Comment by alexleach** [comment]
Ah okay, fair enough. So I'm not going crazy then! I did look for what I thought would have been an obvious option for composer (select a different `composer.json` file), but as that is lacking, it must make it difficult for symfony and in turn kimai, to implement automatic plugin dependency installation.

I'll close this as won't fix, but thanks for explaining. Keeping the instructions in the README is fine with me 🙂
